-- Institucional + fontes de recurso (Operacional)
update public.configuracoes_grupo set
  tempo_agricultura_anos = 25,
  perfil_grupo = 'PRODUTORES RURAIS DESDE 2000, COM AREA DE PLATIO SAFRA / SAFRINHA 2025/26 DE 3.000 HA E 2026/27 DE 6.000 HA. EMPRESÁRIOS, EDER CARLOS MANDOTTI NATURAL DE ASSIS CHATEAUBRIAND - PARANÁ, PRODUTOR RURAL COM MAIS DE 25 ANOS DE EXPERIÊNCIA NO SETOR AGRÍCOLA RESPONSAVEL POR TODO OPERACIONAL E PLANEJAMENTO DE SAFRA E NAGYLA POLLYANNA CRUZ GRADUADA EM DIREITO, ATUA DIRETAMENTE NA ADMINISTRAÇÃO, ORGANIZAÇÃO FINANCEIRA E DOCUMENTAL DAS PROPRIEDADES.',
  fonte_bancario_pct = 85.0,
  fonte_proprio_pct = 15.0,
  fonte_principal_banco = 'BANCO DO BRASIL',
  updated_at = now()
where id = 'c0000000-0000-4000-8000-000000000001'::uuid;
