/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCertificadosRouteImport } from './routes/_authenticated/certificados'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmissoresRouteImport } from './routes/_authenticated/emissores'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedFazendasRouteImport } from './routes/_authenticated/fazendas'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedMaquinarioRouteImport } from './routes/_authenticated/maquinario'
import { Route as AuthenticatedNotasFiscaisRouteImport } from './routes/_authenticated/notas-fiscais'
import { Route as AuthenticatedPassivosRouteImport } from './routes/_authenticated/passivos'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedFinanceiroConciliacaoRouteImport } from './routes/_authenticated/financeiro.conciliacao'
import { Route as AuthenticatedFinanceiroXmlRouteImport } from './routes/_authenticated/financeiro.xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCertificadosRoute =
  AuthenticatedCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmissoresRoute = AuthenticatedEmissoresRouteImport.update({
  id: '/emissores',
  path: '/emissores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFazendasRoute = AuthenticatedFazendasRouteImport.update({
  id: '/fazendas',
  path: '/fazendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaquinarioRoute = AuthenticatedMaquinarioRouteImport.update({
  id: '/maquinario',
  path: '/maquinario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasFiscaisRoute =
  AuthenticatedNotasFiscaisRouteImport.update({
    id: '/notas-fiscais',
    path: '/notas-fiscais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPassivosRoute = AuthenticatedPassivosRouteImport.update({
  id: '/passivos',
  path: '/passivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroConciliacaoRoute =
  AuthenticatedFinanceiroConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroXmlRoute =
  AuthenticatedFinanceiroXmlRouteImport.update({
    id: '/xml',
    path: '/xml',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emissores': typeof AuthenticatedEmissoresRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/fazendas': typeof AuthenticatedFazendasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/maquinario': typeof AuthenticatedMaquinarioRoute
  '/notas-fiscais': typeof AuthenticatedNotasFiscaisRoute
  '/passivos': typeof AuthenticatedPassivosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/xml': typeof AuthenticatedFinanceiroXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emissores': typeof AuthenticatedEmissoresRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/fazendas': typeof AuthenticatedFazendasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/maquinario': typeof AuthenticatedMaquinarioRoute
  '/notas-fiscais': typeof AuthenticatedNotasFiscaisRoute
  '/passivos': typeof AuthenticatedPassivosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/xml': typeof AuthenticatedFinanceiroXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/certificados': typeof AuthenticatedCertificadosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emissores': typeof AuthenticatedEmissoresRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/fazendas': typeof AuthenticatedFazendasRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/_authenticated/maquinario': typeof AuthenticatedMaquinarioRoute
  '/_authenticated/notas-fiscais': typeof AuthenticatedNotasFiscaisRoute
  '/_authenticated/passivos': typeof AuthenticatedPassivosRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/_authenticated/financeiro/xml': typeof AuthenticatedFinanceiroXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/certificados'
    | '/configuracoes'
    | '/dashboard'
    | '/emissores'
    | '/estoque'
    | '/fazendas'
    | '/financeiro'
    | '/maquinario'
    | '/notas-fiscais'
    | '/passivos'
    | '/produtos'
    | '/relatorios'
    | '/usuarios'
    | '/financeiro/conciliacao'
    | '/financeiro/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/certificados'
    | '/configuracoes'
    | '/dashboard'
    | '/emissores'
    | '/estoque'
    | '/fazendas'
    | '/financeiro'
    | '/maquinario'
    | '/notas-fiscais'
    | '/passivos'
    | '/produtos'
    | '/relatorios'
    | '/usuarios'
    | '/financeiro/conciliacao'
    | '/financeiro/xml'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/certificados'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/emissores'
    | '/_authenticated/estoque'
    | '/_authenticated/fazendas'
    | '/_authenticated/financeiro'
    | '/_authenticated/maquinario'
    | '/_authenticated/notas-fiscais'
    | '/_authenticated/passivos'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/usuarios'
    | '/_authenticated/financeiro/conciliacao'
    | '/_authenticated/financeiro/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/certificados': {
      id: '/_authenticated/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof AuthenticatedCertificadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emissores': {
      id: '/_authenticated/emissores'
      path: '/emissores'
      fullPath: '/emissores'
      preLoaderRoute: typeof AuthenticatedEmissoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fazendas': {
      id: '/_authenticated/fazendas'
      path: '/fazendas'
      fullPath: '/fazendas'
      preLoaderRoute: typeof AuthenticatedFazendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maquinario': {
      id: '/_authenticated/maquinario'
      path: '/maquinario'
      fullPath: '/maquinario'
      preLoaderRoute: typeof AuthenticatedMaquinarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas-fiscais': {
      id: '/_authenticated/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais'
      preLoaderRoute: typeof AuthenticatedNotasFiscaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passivos': {
      id: '/_authenticated/passivos'
      path: '/passivos'
      fullPath: '/passivos'
      preLoaderRoute: typeof AuthenticatedPassivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/conciliacao': {
      id: '/_authenticated/financeiro/conciliacao'
      path: '/conciliacao'
      fullPath: '/financeiro/conciliacao'
      preLoaderRoute: typeof AuthenticatedFinanceiroConciliacaoRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/xml': {
      id: '/_authenticated/financeiro/xml'
      path: '/xml'
      fullPath: '/financeiro/xml'
      preLoaderRoute: typeof AuthenticatedFinanceiroXmlRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
  }
}

interface AuthenticatedFinanceiroRouteChildren {
  AuthenticatedFinanceiroConciliacaoRoute: typeof AuthenticatedFinanceiroConciliacaoRoute
  AuthenticatedFinanceiroXmlRoute: typeof AuthenticatedFinanceiroXmlRoute
}

const AuthenticatedFinanceiroRouteChildren: AuthenticatedFinanceiroRouteChildren =
  {
    AuthenticatedFinanceiroConciliacaoRoute:
      AuthenticatedFinanceiroConciliacaoRoute,
    AuthenticatedFinanceiroXmlRoute: AuthenticatedFinanceiroXmlRoute,
  }

const AuthenticatedFinanceiroRouteWithChildren =
  AuthenticatedFinanceiroRoute._addFileChildren(
    AuthenticatedFinanceiroRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCertificadosRoute: typeof AuthenticatedCertificadosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmissoresRoute: typeof AuthenticatedEmissoresRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFazendasRoute: typeof AuthenticatedFazendasRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRouteWithChildren
  AuthenticatedMaquinarioRoute: typeof AuthenticatedMaquinarioRoute
  AuthenticatedNotasFiscaisRoute: typeof AuthenticatedNotasFiscaisRoute
  AuthenticatedPassivosRoute: typeof AuthenticatedPassivosRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCertificadosRoute: AuthenticatedCertificadosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmissoresRoute: AuthenticatedEmissoresRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFazendasRoute: AuthenticatedFazendasRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRouteWithChildren,
  AuthenticatedMaquinarioRoute: AuthenticatedMaquinarioRoute,
  AuthenticatedNotasFiscaisRoute: AuthenticatedNotasFiscaisRoute,
  AuthenticatedPassivosRoute: AuthenticatedPassivosRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
