/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as AuthenticatedAssinaturasRouteImport } from './routes/_authenticated/assinaturas'
import { Route as AuthenticatedCertificadosRouteImport } from './routes/_authenticated/certificados'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEmissoresRouteImport } from './routes/_authenticated/emissores'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedFazendasRouteImport } from './routes/_authenticated/fazendas'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedImportacaoXmlRouteImport } from './routes/_authenticated/importacao-xml'
import { Route as AuthenticatedMaquinarioRouteImport } from './routes/_authenticated/maquinario'
import { Route as AuthenticatedNotasFiscaisRouteImport } from './routes/_authenticated/notas-fiscais'
import { Route as AuthenticatedPassivosRouteImport } from './routes/_authenticated/passivos'
import { Route as AuthenticatedPatrimonioRouteImport } from './routes/_authenticated/patrimonio'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated/producao'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedContabilidadeIndexRouteImport } from './routes/_authenticated/contabilidade/index'
import { Route as AuthenticatedContabilidadeDocumentosRouteImport } from './routes/_authenticated/contabilidade/documentos'
import { Route as AuthenticatedContabilidadeExtratosRouteImport } from './routes/_authenticated/contabilidade/extratos'
import { Route as AuthenticatedContabilidadeFinanceiroRouteImport } from './routes/_authenticated/contabilidade/financeiro'
import { Route as AuthenticatedContabilidadeRelatoriosRouteImport } from './routes/_authenticated/contabilidade/relatorios'
import { Route as AuthenticatedFinanceiroConciliacaoRouteImport } from './routes/_authenticated/financeiro_.conciliacao'
import { Route as AuthenticatedFinanceiroXmlRouteImport } from './routes/_authenticated/financeiro_.xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssinaturasRoute =
  AuthenticatedAssinaturasRouteImport.update({
    id: '/assinaturas',
    path: '/assinaturas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCertificadosRoute =
  AuthenticatedCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmissoresRoute = AuthenticatedEmissoresRouteImport.update({
  id: '/emissores',
  path: '/emissores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFazendasRoute = AuthenticatedFazendasRouteImport.update({
  id: '/fazendas',
  path: '/fazendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportacaoXmlRoute =
  AuthenticatedImportacaoXmlRouteImport.update({
    id: '/importacao-xml',
    path: '/importacao-xml',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaquinarioRoute = AuthenticatedMaquinarioRouteImport.update({
  id: '/maquinario',
  path: '/maquinario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasFiscaisRoute =
  AuthenticatedNotasFiscaisRouteImport.update({
    id: '/notas-fiscais',
    path: '/notas-fiscais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPassivosRoute = AuthenticatedPassivosRouteImport.update({
  id: '/passivos',
  path: '/passivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatrimonioRoute = AuthenticatedPatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContabilidadeIndexRoute =
  AuthenticatedContabilidadeIndexRouteImport.update({
    id: '/contabilidade/',
    path: '/contabilidade/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeDocumentosRoute =
  AuthenticatedContabilidadeDocumentosRouteImport.update({
    id: '/contabilidade/documentos',
    path: '/contabilidade/documentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeExtratosRoute =
  AuthenticatedContabilidadeExtratosRouteImport.update({
    id: '/contabilidade/extratos',
    path: '/contabilidade/extratos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeFinanceiroRoute =
  AuthenticatedContabilidadeFinanceiroRouteImport.update({
    id: '/contabilidade/financeiro',
    path: '/contabilidade/financeiro',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContabilidadeRelatoriosRoute =
  AuthenticatedContabilidadeRelatoriosRouteImport.update({
    id: '/contabilidade/relatorios',
    path: '/contabilidade/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroConciliacaoRoute =
  AuthenticatedFinanceiroConciliacaoRouteImport.update({
    id: '/financeiro_/conciliacao',
    path: '/financeiro/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroXmlRoute =
  AuthenticatedFinanceiroXmlRouteImport.update({
    id: '/financeiro_/xml',
    path: '/financeiro/xml',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/emissores': typeof AuthenticatedEmissoresRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/fazendas': typeof AuthenticatedFazendasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/importacao-xml': typeof AuthenticatedImportacaoXmlRoute
  '/maquinario': typeof AuthenticatedMaquinarioRoute
  '/notas-fiscais': typeof AuthenticatedNotasFiscaisRoute
  '/passivos': typeof AuthenticatedPassivosRoute
  '/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/contabilidade/documentos': typeof AuthenticatedContabilidadeDocumentosRoute
  '/contabilidade/extratos': typeof AuthenticatedContabilidadeExtratosRoute
  '/contabilidade/financeiro': typeof AuthenticatedContabilidadeFinanceiroRoute
  '/contabilidade/relatorios': typeof AuthenticatedContabilidadeRelatoriosRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/xml': typeof AuthenticatedFinanceiroXmlRoute
  '/contabilidade/': typeof AuthenticatedContabilidadeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/certificados': typeof AuthenticatedCertificadosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/emissores': typeof AuthenticatedEmissoresRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/fazendas': typeof AuthenticatedFazendasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/importacao-xml': typeof AuthenticatedImportacaoXmlRoute
  '/maquinario': typeof AuthenticatedMaquinarioRoute
  '/notas-fiscais': typeof AuthenticatedNotasFiscaisRoute
  '/passivos': typeof AuthenticatedPassivosRoute
  '/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/contabilidade/documentos': typeof AuthenticatedContabilidadeDocumentosRoute
  '/contabilidade/extratos': typeof AuthenticatedContabilidadeExtratosRoute
  '/contabilidade/financeiro': typeof AuthenticatedContabilidadeFinanceiroRoute
  '/contabilidade/relatorios': typeof AuthenticatedContabilidadeRelatoriosRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/xml': typeof AuthenticatedFinanceiroXmlRoute
  '/contabilidade': typeof AuthenticatedContabilidadeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/_authenticated/assinaturas': typeof AuthenticatedAssinaturasRoute
  '/_authenticated/certificados': typeof AuthenticatedCertificadosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/emissores': typeof AuthenticatedEmissoresRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/fazendas': typeof AuthenticatedFazendasRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/importacao-xml': typeof AuthenticatedImportacaoXmlRoute
  '/_authenticated/maquinario': typeof AuthenticatedMaquinarioRoute
  '/_authenticated/notas-fiscais': typeof AuthenticatedNotasFiscaisRoute
  '/_authenticated/passivos': typeof AuthenticatedPassivosRoute
  '/_authenticated/patrimonio': typeof AuthenticatedPatrimonioRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/contabilidade/documentos': typeof AuthenticatedContabilidadeDocumentosRoute
  '/_authenticated/contabilidade/extratos': typeof AuthenticatedContabilidadeExtratosRoute
  '/_authenticated/contabilidade/financeiro': typeof AuthenticatedContabilidadeFinanceiroRoute
  '/_authenticated/contabilidade/relatorios': typeof AuthenticatedContabilidadeRelatoriosRoute
  '/_authenticated/financeiro_/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/_authenticated/financeiro_/xml': typeof AuthenticatedFinanceiroXmlRoute
  '/_authenticated/contabilidade/': typeof AuthenticatedContabilidadeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/trocar-senha'
    | '/assinaturas'
    | '/certificados'
    | '/clientes'
    | '/conciliacao'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/documentos'
    | '/emissores'
    | '/estoque'
    | '/fazendas'
    | '/financeiro'
    | '/importacao-xml'
    | '/maquinario'
    | '/notas-fiscais'
    | '/passivos'
    | '/patrimonio'
    | '/producao'
    | '/produtos'
    | '/relatorios'
    | '/usuarios'
    | '/contabilidade/documentos'
    | '/contabilidade/extratos'
    | '/contabilidade/financeiro'
    | '/contabilidade/relatorios'
    | '/financeiro/conciliacao'
    | '/financeiro/xml'
    | '/contabilidade/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/trocar-senha'
    | '/assinaturas'
    | '/certificados'
    | '/clientes'
    | '/conciliacao'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/documentos'
    | '/emissores'
    | '/estoque'
    | '/fazendas'
    | '/financeiro'
    | '/importacao-xml'
    | '/maquinario'
    | '/notas-fiscais'
    | '/passivos'
    | '/patrimonio'
    | '/producao'
    | '/produtos'
    | '/relatorios'
    | '/usuarios'
    | '/contabilidade/documentos'
    | '/contabilidade/extratos'
    | '/contabilidade/financeiro'
    | '/contabilidade/relatorios'
    | '/financeiro/conciliacao'
    | '/financeiro/xml'
    | '/contabilidade'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/trocar-senha'
    | '/_authenticated/assinaturas'
    | '/_authenticated/certificados'
    | '/_authenticated/clientes'
    | '/_authenticated/conciliacao'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contratos'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/emissores'
    | '/_authenticated/estoque'
    | '/_authenticated/fazendas'
    | '/_authenticated/financeiro'
    | '/_authenticated/importacao-xml'
    | '/_authenticated/maquinario'
    | '/_authenticated/notas-fiscais'
    | '/_authenticated/passivos'
    | '/_authenticated/patrimonio'
    | '/_authenticated/producao'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/usuarios'
    | '/_authenticated/contabilidade/documentos'
    | '/_authenticated/contabilidade/extratos'
    | '/_authenticated/contabilidade/financeiro'
    | '/_authenticated/contabilidade/relatorios'
    | '/_authenticated/financeiro_/conciliacao'
    | '/_authenticated/financeiro_/xml'
    | '/_authenticated/contabilidade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assinaturas': {
      id: '/_authenticated/assinaturas'
      path: '/assinaturas'
      fullPath: '/assinaturas'
      preLoaderRoute: typeof AuthenticatedAssinaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificados': {
      id: '/_authenticated/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof AuthenticatedCertificadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emissores': {
      id: '/_authenticated/emissores'
      path: '/emissores'
      fullPath: '/emissores'
      preLoaderRoute: typeof AuthenticatedEmissoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fazendas': {
      id: '/_authenticated/fazendas'
      path: '/fazendas'
      fullPath: '/fazendas'
      preLoaderRoute: typeof AuthenticatedFazendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importacao-xml': {
      id: '/_authenticated/importacao-xml'
      path: '/importacao-xml'
      fullPath: '/importacao-xml'
      preLoaderRoute: typeof AuthenticatedImportacaoXmlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maquinario': {
      id: '/_authenticated/maquinario'
      path: '/maquinario'
      fullPath: '/maquinario'
      preLoaderRoute: typeof AuthenticatedMaquinarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas-fiscais': {
      id: '/_authenticated/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais'
      preLoaderRoute: typeof AuthenticatedNotasFiscaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passivos': {
      id: '/_authenticated/passivos'
      path: '/passivos'
      fullPath: '/passivos'
      preLoaderRoute: typeof AuthenticatedPassivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patrimonio': {
      id: '/_authenticated/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof AuthenticatedPatrimonioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/': {
      id: '/_authenticated/contabilidade/'
      path: '/contabilidade'
      fullPath: '/contabilidade/'
      preLoaderRoute: typeof AuthenticatedContabilidadeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/documentos': {
      id: '/_authenticated/contabilidade/documentos'
      path: '/contabilidade/documentos'
      fullPath: '/contabilidade/documentos'
      preLoaderRoute: typeof AuthenticatedContabilidadeDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/extratos': {
      id: '/_authenticated/contabilidade/extratos'
      path: '/contabilidade/extratos'
      fullPath: '/contabilidade/extratos'
      preLoaderRoute: typeof AuthenticatedContabilidadeExtratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/financeiro': {
      id: '/_authenticated/contabilidade/financeiro'
      path: '/contabilidade/financeiro'
      fullPath: '/contabilidade/financeiro'
      preLoaderRoute: typeof AuthenticatedContabilidadeFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contabilidade/relatorios': {
      id: '/_authenticated/contabilidade/relatorios'
      path: '/contabilidade/relatorios'
      fullPath: '/contabilidade/relatorios'
      preLoaderRoute: typeof AuthenticatedContabilidadeRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro_/conciliacao': {
      id: '/_authenticated/financeiro_/conciliacao'
      path: '/financeiro/conciliacao'
      fullPath: '/financeiro/conciliacao'
      preLoaderRoute: typeof AuthenticatedFinanceiroConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro_/xml': {
      id: '/_authenticated/financeiro_/xml'
      path: '/financeiro/xml'
      fullPath: '/financeiro/xml'
      preLoaderRoute: typeof AuthenticatedFinanceiroXmlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssinaturasRoute: typeof AuthenticatedAssinaturasRoute
  AuthenticatedCertificadosRoute: typeof AuthenticatedCertificadosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEmissoresRoute: typeof AuthenticatedEmissoresRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFazendasRoute: typeof AuthenticatedFazendasRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedImportacaoXmlRoute: typeof AuthenticatedImportacaoXmlRoute
  AuthenticatedMaquinarioRoute: typeof AuthenticatedMaquinarioRoute
  AuthenticatedNotasFiscaisRoute: typeof AuthenticatedNotasFiscaisRoute
  AuthenticatedPassivosRoute: typeof AuthenticatedPassivosRoute
  AuthenticatedPatrimonioRoute: typeof AuthenticatedPatrimonioRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedContabilidadeDocumentosRoute: typeof AuthenticatedContabilidadeDocumentosRoute
  AuthenticatedContabilidadeExtratosRoute: typeof AuthenticatedContabilidadeExtratosRoute
  AuthenticatedContabilidadeFinanceiroRoute: typeof AuthenticatedContabilidadeFinanceiroRoute
  AuthenticatedContabilidadeRelatoriosRoute: typeof AuthenticatedContabilidadeRelatoriosRoute
  AuthenticatedFinanceiroConciliacaoRoute: typeof AuthenticatedFinanceiroConciliacaoRoute
  AuthenticatedFinanceiroXmlRoute: typeof AuthenticatedFinanceiroXmlRoute
  AuthenticatedContabilidadeIndexRoute: typeof AuthenticatedContabilidadeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssinaturasRoute: AuthenticatedAssinaturasRoute,
  AuthenticatedCertificadosRoute: AuthenticatedCertificadosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEmissoresRoute: AuthenticatedEmissoresRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFazendasRoute: AuthenticatedFazendasRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedImportacaoXmlRoute: AuthenticatedImportacaoXmlRoute,
  AuthenticatedMaquinarioRoute: AuthenticatedMaquinarioRoute,
  AuthenticatedNotasFiscaisRoute: AuthenticatedNotasFiscaisRoute,
  AuthenticatedPassivosRoute: AuthenticatedPassivosRoute,
  AuthenticatedPatrimonioRoute: AuthenticatedPatrimonioRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedContabilidadeDocumentosRoute:
    AuthenticatedContabilidadeDocumentosRoute,
  AuthenticatedContabilidadeExtratosRoute:
    AuthenticatedContabilidadeExtratosRoute,
  AuthenticatedContabilidadeFinanceiroRoute:
    AuthenticatedContabilidadeFinanceiroRoute,
  AuthenticatedContabilidadeRelatoriosRoute:
    AuthenticatedContabilidadeRelatoriosRoute,
  AuthenticatedFinanceiroConciliacaoRoute:
    AuthenticatedFinanceiroConciliacaoRoute,
  AuthenticatedFinanceiroXmlRoute: AuthenticatedFinanceiroXmlRoute,
  AuthenticatedContabilidadeIndexRoute: AuthenticatedContabilidadeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
