// This file is automatically generated. Do not edit it directly.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15";
  };
  public: {
    Tables: {
      certificados: {
        Row: {
          ativo: boolean;
          cnpj: string | null;
          created_at: string;
          deleted_at: string | null;
          emissor_id: string;
          id: string;
          nome: string;
          senha_referencia: string | null;
          tipo: Database["public"]["Enums"]["tipo_certificado"];
          titular: string | null;
          updated_at: string;
          validade: string | null;
        };
        Insert: {
          ativo?: boolean;
          cnpj?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          emissor_id: string;
          id?: string;
          nome: string;
          senha_referencia?: string | null;
          tipo?: Database["public"]["Enums"]["tipo_certificado"];
          titular?: string | null;
          updated_at?: string;
          validade?: string | null;
        };
        Update: {
          ativo?: boolean;
          cnpj?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          emissor_id?: string;
          id?: string;
          nome?: string;
          senha_referencia?: string | null;
          tipo?: Database["public"]["Enums"]["tipo_certificado"];
          titular?: string | null;
          updated_at?: string;
          validade?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "certificados_emissor_id_fkey";
            columns: ["emissor_id"];
            isOneToOne: false;
            referencedRelation: "emissores";
            referencedColumns: ["id"];
          },
        ];
      };
      emissores: {
        Row: {
          ativo: boolean;
          cep: string | null;
          cidade: string | null;
          cnpj: string;
          created_at: string;
          deleted_at: string | null;
          email: string | null;
          endereco: string | null;
          id: string;
          inscricao_estadual: string | null;
          nome_fantasia: string | null;
          razao_social: string;
          telefone: string | null;
          uf: string | null;
          updated_at: string;
        };
        Insert: {
          ativo?: boolean;
          cep?: string | null;
          cidade?: string | null;
          cnpj: string;
          created_at?: string;
          deleted_at?: string | null;
          email?: string | null;
          endereco?: string | null;
          id?: string;
          inscricao_estadual?: string | null;
          nome_fantasia?: string | null;
          razao_social: string;
          telefone?: string | null;
          uf?: string | null;
          updated_at?: string;
        };
        Update: {
          ativo?: boolean;
          cep?: string | null;
          cidade?: string | null;
          cnpj?: string;
          created_at?: string;
          deleted_at?: string | null;
          email?: string | null;
          endereco?: string | null;
          id?: string;
          inscricao_estadual?: string | null;
          nome_fantasia?: string | null;
          razao_social?: string;
          telefone?: string | null;
          uf?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      fazendas: {
        Row: {
          area_hectares: number | null;
          ativo: boolean;
          car: string | null;
          codigo: string | null;
          created_at: string;
          deleted_at: string | null;
          emissor_id: string;
          id: string;
          inscricao_estadual: string | null;
          municipio: string | null;
          nome: string;
          uf: string | null;
          updated_at: string;
        };
        Insert: {
          area_hectares?: number | null;
          ativo?: boolean;
          car?: string | null;
          codigo?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          emissor_id: string;
          id?: string;
          inscricao_estadual?: string | null;
          municipio?: string | null;
          nome: string;
          uf?: string | null;
          updated_at?: string;
        };
        Update: {
          area_hectares?: number | null;
          ativo?: boolean;
          car?: string | null;
          codigo?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          emissor_id?: string;
          id?: string;
          inscricao_estadual?: string | null;
          municipio?: string | null;
          nome?: string;
          uf?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "fazendas_emissor_id_fkey";
            columns: ["emissor_id"];
            isOneToOne: false;
            referencedRelation: "emissores";
            referencedColumns: ["id"];
          },
        ];
      };
      papeis_usuario: {
        Row: {
          created_at: string;
          id: string;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          role: Database["public"]["Enums"]["app_role"];
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          role?: Database["public"]["Enums"]["app_role"];
          user_id?: string;
        };
        Relationships: [];
      };
      perfis: {
        Row: {
          ativo: boolean;
          created_at: string;
          email: string | null;
          id: string;
          nome: string;
          perfil: Database["public"]["Enums"]["perfil_usuario"];
          telefone: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          ativo?: boolean;
          created_at?: string;
          email?: string | null;
          id?: string;
          nome?: string;
          perfil?: Database["public"]["Enums"]["perfil_usuario"];
          telefone?: string | null;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          ativo?: boolean;
          created_at?: string;
          email?: string | null;
          id?: string;
          nome?: string;
          perfil?: Database["public"]["Enums"]["perfil_usuario"];
          telefone?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      perfis_acesso: {
        Row: {
          created_at: string;
          id: string;
          pode_editar: boolean;
          pode_ver: boolean;
          rota: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          pode_editar?: boolean;
          pode_ver?: boolean;
          rota: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          pode_editar?: boolean;
          pode_ver?: boolean;
          rota?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      has_role: {
        Args: {
          _role: Database["public"]["Enums"]["app_role"];
          _user_id: string;
        };
        Returns: boolean;
      };
      is_admin: { Args: { _user_id: string }; Returns: boolean };
      is_contabilidade: { Args: { _user_id: string }; Returns: boolean };
      pode_editar: { Args: { _user_id: string }; Returns: boolean };
      pode_editar_rota: {
        Args: { _rota: string; _user_id: string };
        Returns: boolean;
      };
      pode_ver_rota: {
        Args: { _rota: string; _user_id: string };
        Returns: boolean;
      };
      rota_e_fiscal_financeira: { Args: { _rota: string }; Returns: boolean };
    };
    Enums: {
      app_role: "administrador" | "gestor" | "operador" | "visualizador";
      perfil_usuario: "admin" | "funcionario" | "contabilidade";
      tipo_certificado: "A1" | "A3";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      app_role: ["administrador", "gestor", "operador", "visualizador"],
      perfil_usuario: ["admin", "funcionario", "contabilidade"],
      tipo_certificado: ["A1", "A3"],
    },
  },
} as const;
